### ISSUE TITLE
After updating the plugin broke

### ISSUE THREAD

**Issue by loqus** [studioespresso/craft-unsplash#12]
I got a ReflectionException error after the plugin directory was renamed. 
By changing craft3-unsplash/src/assetbundles/SplashingImages/ to craft3-unsplash/src/assetbundles/splashingimages/ it worked again

**Comment by janhenckens** [comment]
Oops, my bad! @loqus Just pushed an updat that should fix this, can you install that and try again?

**Comment by loqus** [comment]
All good! Thanks for the update
