### ISSUE TITLE
Broken in latest update (2.1.3) - Incorrect path (capitalisation issue)

### ISSUE THREAD

**Issue by croxton** [studioespresso/craft-unsplash#13]
```
yii\base\InvalidArgumentException: The file or directory to be published does not exist: /var/www/html/vendor/studioespresso/craft-splashingimages/src/assetbundles/splashingimages/dist in /var/www/html/vendor/yiisoft/yii2/web/AssetManager.php:455
```

I think the path here should be `@studioespresso/splashingimages/assetbundles/SplashingImages/dist` ?
https://github.com/studioespresso/craft3-unsplash/blob/19dab75cc0181c0b14727acb8b34ba64d57c7d89/src/assetbundles/SplashingImages/SplashingImagesAsset.php#L46

**Comment by janhenckens** [comment]
Hey Mark, sorry about that. Hard to test these case sensitive issues out on a system that isn't case sensitive itself. I'll try to get it on a server somewhere to try and debug asap!

**Comment by croxton** [comment]
Thanks for the quick response! Fully working again.
