### ISSUE TITLE
Results url URL breaks Plugin when searching for multiple terms

### ISSUE THREAD

**Issue by klick** [studioespresso/craft-unsplash#16]
I noticed the search breaks the plugin at least on my hosting. This:

`https://example.com/admin/splashing-images/search/Term1%20Term2%20AnotherTerm/1?site=default`

using url encoded spaces in the result url throws a 403.
Whereas replacing them with dashes (`-`):

`https://example.com/admin/splashing-images/search/Term1-Term2-AnotherTerm/1?site=default`

makes the plugin behave as expected. Which is also analogue to the search model on the unsplash website.

Is there anyway to fix this? Or could someone point me to the code in the plugin so I can do that myself? Should be not so hard once I know where that lives.

**Comment by janhenckens** [comment]
Thanks for reporting this, not sure why I wrote it this way... Anyway, fixed in 3.0.1!

**Comment by klick** [comment]
Thank you!

Now though the paging for search terms seem has stopped. :) Results are capped at appr. 30 images with no infinite loading being triggered at scrolling down (“No more pages to load”).

**Comment by janhenckens** [comment]
Forgot to include the search term in the "next" url, should be fixed in 3.0.2.

**Comment by klick** [comment]
Works now.

Thanks again!
