### ISSUE TITLE
Ability to specify control panel path or just grab it from general.php.

### ISSUE THREAD

**Issue by klick** [studioespresso/craft-unsplash#3]
I have a habit of customizing the path to my control panel which is breaking the search function of this useful plugin.

**Comment by janhenckens** [comment]
Yeah, I didn't think of that. Should be easy enough to make setting for it. Stay tuned :)

**Comment by janhenckens** [comment]
This should done based on the `cpTrigger` setting.

**Comment by klick** [comment]
Preferably, yes.

**Comment by janhenckens** [comment]
Just released an update that includes this, can you give it a try?

**Comment by klick** [comment]
Works just fine. Thanks!

**Comment by janhenckens** [comment]
👍🏻
